"""delete unuseful field update_time in user model

Revision ID: c1932bac5a5f
Revises: d5e93f667e96
Create Date: 2025-05-15 22:53:51.004209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1932bac5a5f'
down_revision: Union[str, None] = 'd5e93f667e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
